### ISSUE TITLE
redundant machine translations

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-cli#1] opened 2024-04-15 13:25 UTC
See message on discord

**Comment by jldec** [comment] 2024-04-15 15:33
https://discord.com/channels/897438559458430986/1070750156644962434/1229261688826761237

Hi @pboling 
Could it be that the progress bar is showing calls to our rpc server but no translation is actually being performed?
You can tell when this happens if the machine translate command prints the progress bar, but does not log any translations. Each of those would appear as a line in the output which looks like: 
```
ℹ Machine translated message "<key>"
``` 
If you are seeing those translation logs in the output on every run that would be unexpected, and probably a bug.

**Comment by pboling** [comment] 2024-04-15 18:12
No, that's definitely not it.

Back when I did have translations that were missing I would see that line, IIRC.

The only output I see that evidences connections being made for no reason I can think of is this:
```
 ERROR  ENOTFOUND fetch failed
 ```
 
 Aside from that it is also frequently very slow, which indicates latency, when a straight yaml/json text parse & compare should be very, very fast, with very little variance in overall duration.

**Comment by pboling** [comment] 2024-04-15 18:37
Also worth noting here that the original output I copied and pasted:
```
🤖 Machine translating messages | ████████████████████████████████████████ | 99% | 319/320 Messages
```
was from a time when it got stuck there.  I waited a long time, and it never progressed to finish that last message.  I had to `CTRL-C` to kill the process, and run it again.

It was on the subsequent run that I saw the error:
```
 ERROR  ENOTFOUND fetch failed
```
though at least it did finish.  I can't understand why any network connection was attempted.

**Comment by pboling** [comment] 2024-04-15 19:24
Another issue is with the misleading phrasing.

"Machine translating messages" is a false statement, when all have already been translated.

"Checking for translations" should come first. If all present then machine translating should never happen.

**Comment by samuelstroschein** [comment] 2024-04-16 00:17
@felix.haeberle why is this in backlog and not todo?

**Comment by jldec** [comment] 2024-04-16 11:35
I have opened separate issue #2 (INCLI-2) related to unnecessary network requests.
We can keep this issue open if we believe there are still redundant calls to the google translate service.

**Comment by jldec** [comment] 2024-04-29 20:44
closing as duplicate of INCLI-2

**Comment by pboling** [comment] 2024-04-30 19:45
@jldec I think you accidentally didn't close it ;)

**Comment by pboling** [comment] 2024-05-21 05:03
This can be closed

**Closed as completed** 2024-05-21 13:25 UTC
